name: PlatformIO Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install Project Dependencies
        run: |
          pio pkg install --global --no-interactive

      - name: Build Project
        run: |
          pio run -v  # Добавлен verbose вывод

      - name: Code Size Report
        run: |
          pio run -t size

      - name: Check Code Style
        run: |
          pio check --flags "-DCPPCHECK --verbose"
        continue-on-error: true
